items = [
    {
        "room":"Outdoor",
        "items":[
                    {
                        "id":6,
                        "name":"front_bell",
                        "type":"doorbell"
                    }
                ]
    },
    {
        "room":"Living Room",
        "items":[
                    {
                        "id":1,
                        "name":"light1",
                        "type":"light"
                    },
                    {   
                        "id":2,
                        "name":"light2",
                        "type":"light"
                    },
                    {   
                        "id":3,
                        "name":"light3",
                        "type":"light"
                    }
                ]
    },
    {
        "room":"Bed Room",
        "items":[
                    {
                        "id":4,
                        "name":"light1",
                        "type":"light"
                    },
                    {   
                        "id":5,
                        "name":"light2",
                        "type":"light"
                    }
                ]
    }
]
;