items = [
    {
        "room":"Outdoor",
        "items":[
                    {
                        "id":6,
                        "name":"front_bell",
                        "type":"doorbell"
                    },
                    {
                        "id":12,
                        "name":"camera1",
                        "type":"camera",
                        "stream":"rtsp://132.239.12.145/axis-media/media.amp"
                    }
                ]
    },
    {
        "room":"Living Room",
        "items":[
                    {
                        "id":1,
                        "name":"light1",
                        "type":"light"
                    },
                    {   
                        "id":2,
                        "name":"light2",
                        "type":"light"
                    },
                    {   
                        "id":3,
                        "name":"light3",
                        "type":"light"
                    },
                    {
                        "id":7,
                        "name":"switch1",
                        "type":"switch"
                    },
                    {
                        "id":8,
                        "name":"switch1",
                        "type":"switch"
                    }
                ]
    },
    {
        "room":"Bed Room",
        "items":[
                    {
                        "id":4,
                        "name":"light1",
                        "type":"light"
                    },
                    {   
                        "id":5,
                        "name":"light2",
                        "type":"light"
                    },
                    {
                        "id":9,
                        "name":"multiswitch1",
                        "type":"multiswitch",
                        "items":[
                            {
                                "id":10,
                                "name":"switch1",
                                "type":"switch"
                            },
                            {
                                "id":11,
                                "name":"switch2",
                                "type":"switch"
                            }
                        ]
                    }
                ]
    }
]
;